### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions-api#20]
Via Swagger

**Comment by cfeeney-va** [comment]
https://coderwall.com/p/bjk3pa/documenting-rails-based-rest-api-using-swagger-ui

also add the following:
https://github.com/richhollis/swagger-docs/issues/75

**Comment by ayaleloehr** [comment]
No longer via swagger; apipie now. @cfeeney-va is on it.
