### ISSUE TITLE
Use va_rx in prescriptions-api

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions-api#27]
should add va-rx to the prescription-api gemfile using a github URL (instead of publishing gem yet).

**Comment by saneshark** [comment]
Technically this is done, but we're not using it for 100% of the endpoints yet.

**Comment by ayaleloehr** [comment]
Done in some combination of https://github.com/department-of-veterans-affairs/prescriptions-api/pull/30 , https://github.com/department-of-veterans-affairs/prescriptions-api/pull/33 , https://github.com/department-of-veterans-affairs/prescriptions-api/pull/37
