### ISSUE TITLE
When / how does the value of `is-refillable` change?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/prescriptions-api#54]
In the mock API, there are two values that affect whether a prescription can be refilled: 
`data.attributes.is-refillable` and `data.attributes.refill-remaining`. 

If `data.attributes.refill-remaining === 0`, does the value of `data.attributes.is-refillable` change to false? Or are those two attributes always independent of each other?

Affects department-of-veterans-affairs/vets-website#2576

**Comment by ayaleloehr** [comment]
Our normal contact for these questions (Carnetta) is out this week. Wondering if @gnakm or @angel or @goldenmeanie ran into this before or had already asked this and know the answer?

**Comment by U-DON** [comment]
I think I recall there being a document that mapped the properties from the API to the visual elements in the design. It'd be useful to have it pinned in Slack.

**Comment by angel** [comment]
If `data.attributes.refill-remaining === 0`, `data.attributes.is-refillable` should change to false. The Veteran should not be able to try to refill a prescription with 0 refills, but be directed to contact their provider to get a renewal ideally. /cc @gnakm @goldenmeanie

**Comment by U-DON** [comment]
With that being the case, what attribute(s) should cause the "Refill requested" text to appear?

**Comment by angel** [comment]
I don't know the exact attribute, but the refill button should change to "Refill requested" after a Veteran goes through the flow of ordering a refill for that prescription.

**Comment by webinista** [comment]
I'd say `data.attributes.is-refillable`. I think there will be some medications included that _aren't_ refillable online, but may have refills available. `data.attributes.is-refillable` is the canonical value in both cases.
