### ISSUE TITLE
refillStatus not being returned

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions-api#58]
refillStatus should be an attribute on a prescription that is returned from the API. It is not currently for some reason (likely this is in the gem, so this is the wrong repo, but typing here anyways).  I believe this is a bug.

**Comment by saneshark** [comment]
@ayaleloehr - currently the values for refill_status will lowerCamel, are we ok with that or should I go ahead and make the values into snake case?

**Comment by ayaleloehr** [comment]
Let's provide it exactly as is for now. Thus far we haven't messed with values at all (as you say, only keys...) so let's keep doing that for this first pass. We can have a larger vets.gov discussion on this, fitting with our keys discussion that started on Friday and is documented [here](https://github.com/department-of-veterans-affairs/dsva-how-we-work/issues/52), but don't want that to block movement here.
