### ISSUE TITLE
links shouldn't refer to localhost

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions-api#59]
If you go to: https://dev.vets.gov/prescriptions-api/rx/v1/prescriptions/active

All the links refer to localhost instead of the correct hostname. Example:

```
"links": {
"self": "http://localhost:3000/rx/v1/prescriptions/1435525",
"tracking": "http://localhost:3000/rx/v1/prescriptions/1435525/trackings"
}
```

**Comment by ayaleloehr** [comment]
And they also shouldn't have the port on there either when localhost is changed to dev.vets.gov or whatever other hostname it will be.

**Comment by saneshark** [comment]
@ayaleloehr I believe this is automatically fixed, as long as vets-api sets HOSTNAME env variable.

Let's leave this issue open and confirm once reverse proxy is modified to point to vets-api / platform-api instead of prescriptions-api
