### ISSUE TITLE
Add URLs to each shipment in the trackings collection

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions-api#60]
Copying from Slack:

"UPS and USPS are the two carriers. It looks like for USPS if you go to:

https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=X

Where X is replaced with the tracking number, that will send you to the right page. And for USPS if you go to:

https://tools.usps.com/go/TrackConfirmAction?tLabels=X

Where X is replaced with the tracking number, that will send you to the right page.

I think it would be ideal if we could pass these from the API instead of making the frontend hardcode these in. @saneshark what are your thoughts on adding a `tracking-url` field to the collection of tracked prescriptions we're returning that will create the right URL depending on the deliveryService?"

**Comment by saneshark** [comment]
Going to think on this one a bit and address it as a separate PR.

**Comment by ayaleloehr** [comment]
That's fine. Does the logic make sense though?  I think we just have two constants (https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums= and https://tools.usps.com/go/TrackConfirmAction?tLabels=) and concatenate those with the tracking number to create a new field called tracking-url?

**Comment by saneshark** [comment]
Yea, it totally makes sense, just want to think of a good way to abstract that out and put the hostnames for the carriers into a constant somewhere. I might be able to address in this same PR, but I'll circle back to it.
