### ISSUE TITLE
move va_rx into vets-api/lib

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/prescriptions-api#66]
initially will do clean move, with only minor refactor as necessary, but eventually will refactor into more abstract, reusable components once we do something similar for secure_messaging.

**Comment by ayaleloehr** [comment]
initial review today.

**Comment by saneshark** [comment]
This took a little longer than originally intended, some minor refactors are in place, but greater refactors will come as we begin to move secure messaging into vets-api in a similar fashion. There is a PR (https://github.com/department-of-veterans-affairs/vets-api/pull/88) open for this.
